require:
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  inherit_mode:
    merge:
      - Include
  Include:
    - .*/*.rb

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 118

Metrics/AbcSize:
  Max: 150

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 100

Metrics/ParameterLists:
  CountKeywordArgs: false

# Incompatible with Sorbet
Naming/BlockForwarding:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: false
Sorbet/StrictSigil:
  Enabled: true
  Include:
    - src/server.rb
    - src/github_client.rb
Sorbet/StrongSigil:
  Enabled: true
  Exclude:
    - src/server.rb
    - src/github_client.rb
    - src/octokit/*.rb

Style/AndOr:
  EnforcedStyle: always

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/MutableConstant:
  EnforcedStyle: strict

Style/NumericLiterals:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/UnlessLogicalOperators:
  Enabled: true
  EnforcedStyle: forbid_logical_operators
