gem:
  exclude:
    - ast
    - base64
    - benchmark
    - erubi
    - faraday-multipart
    - faraday-net_http
    - faraday-retry
    - logger
    - json
    - language_server-protocol
    - lint_roller
    - multipart-post
    - mustermann
    - net-http
    - netrc
    - nio4r
    - orka_api_client
    - parallel
    - parser
    - prism
    - public_suffix
    - puma
    - racc
    - rack-protection
    - rackup
    - rainbow
    - rbi
    - rbs
    - regexp_parser
    - rubocop-ast
    - rubocop-performance
    - rubocop-sorbet
    - rubocop
    - ruby-progressbar
    - ruby2_keywords
    - sawyer
    - spoom
    - tapioca
    - thor
    - tilt
    - unicode-display_width
    - unicode-emoji
    - uri
    - webrick
    - yard-sorbet
    - yard
