name: Test and deploy to GKE

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: development

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@472790540115ce5bd69d399a020189a8c87d641f # v1.247.0
      with:
        bundler-cache: true

    - name: Check Tapioca excludes
      run: bundle exec ./.github/scripts/tapioca-exclude-check.rb

    - name: Check RBI shims
      run: bundle exec tapioca check-shims

    - name: Run Sorbet typecheck
      run: bundle exec srb tc

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Build Docker image
      run: docker build --build-arg RUBY_VERSION="$(<.ruby-version)" .

  deploy:
    needs: checks
    if: github.repository_owner == 'Homebrew' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    env:
      GOOGLE_REGISTRY: us-central1-docker.pkg.dev
      GOOGLE_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/homebrew-docker/ci-orchestrator:${{ github.sha }}
      AWS_REGISTRY: "${{ secrets.AWS_PROJECT_ID }}.dkr.ecr.us-east-1.amazonaws.com/orchestrator-ecr"
      AWS_IMAGE: "${{ secrets.AWS_PROJECT_ID }}.dkr.ecr.us-east-1.amazonaws.com/orchestrator-ecr:${{ github.sha }}"
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Authenticate to Google Cloud
      id: gcloud-auth
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      with:
        token_format: access_token
        workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/ci-orchestrator-deploy/providers/github-actions
        service_account: ci-orchestrator-deploy@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

    - name: Login GOOGLE docker registry
      env:
        GCLOUD_ACCESS_TOKEN: ${{ steps.gcloud-auth.outputs.access_token }}
      run: |-
        echo "$GCLOUD_ACCESS_TOKEN" | docker login -u oauth2accesstoken --password-stdin "$GOOGLE_REGISTRY"

    - name: Build Docker image (GOOGLE)
      run: |-
        docker build --tag "$GOOGLE_IMAGE" --build-arg RUBY_VERSION="$(<.ruby-version)" .

    - name: Publish Docker image (GOOGLE)
      run: |-
        docker push "$GOOGLE_IMAGE"

    - name: Logout from GOOGLE docker registry
      run: |-
        docker logout "$GOOGLE_REGISTRY"

    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_PROJECT_ID }}:role/GithubActionsRoleECRPush
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076

    - name: Retag image (AWS)
      run: |-
        docker image tag "$GOOGLE_IMAGE" "$AWS_IMAGE"

    - name: Push to AWS
      # Not deployed yet, needs missing infrastructure
      run: |
        docker push "$AWS_IMAGE"

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@d0cee45012069b163a631894b98904a9e6723729 # v2.3.3
      with:
        cluster_name: ci-orchestrator
        location: us-central1-c

    - name: Deploy Kubernetes
      working-directory: deployment
      env:
        CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        ORKA_IP: ${{ secrets.ORKA_IP }}
        ORKA_DOMAIN: ${{ secrets.ORKA_DOMAIN }}
        ORKA_K8S_DOMAIN: ${{ secrets.ORKA_K8S_DOMAIN }}
        GITHUB_CLIENT_ID: ${{ secrets.GITHUBCLIENT_ID }}
        GITHUB_ORGANISATION: ${{ github.repository_owner }}
        GITHUB_INSTALLATION_ID: ${{ secrets.GITHUBAPP_INSTALLATION_ID }}
      run: |-
        sed -f /dev/stdin deployment.yml.in > deployment.yml <<SED_SCRIPT
          s|@IMAGE@|$GOOGLE_IMAGE|g
          s|@CERTBOT_EMAIL@|$CERTBOT_EMAIL|g
          s|@ORKA_IP@|$ORKA_IP|g
          s|@ORKA_DOMAIN@|$ORKA_DOMAIN|g
          s|@ORKA_K8S_DOMAIN@|$ORKA_K8S_DOMAIN|g
        SED_SCRIPT
        sed -f /dev/stdin config.yml.in > config.yml <<SED_SCRIPT
          s|@DOMAIN@|$DOMAIN|g
          s|@PUBLIC_IP@|$PUBLIC_IP|g
          s|@ORKA_DOMAIN@|$ORKA_DOMAIN|g
          s|@GITHUB_CLIENT_ID@|$GITHUB_CLIENT_ID|g
          s|@GITHUB_ORGANISATION@|$GITHUB_ORGANISATION|g
          s|@GITHUB_INSTALLATION_ID@|$GITHUB_INSTALLATION_ID|g
        SED_SCRIPT
        kubectl apply -f .
        kubectl rollout status statefulset/ci-orchestrator
